org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

mod_id=cinderlib
mod_name=CinderLib
mod_version=0.1.0
mod_group=dev.cinderlib

minecraft_version=26.1.2
java_version=25

fabric_loom_version=1.18.2
fabric_loader_version=0.19.5
fabric_api_version=0.155.3+26.1.2
neoforge_version=26.1.2.109
moddev_version=2.0.147
architectury_api_version=20.1.15
modmenu_version=18.0.1
jei_version=29.40.0.101
jade_version=26.1.11
geckolib_version=5.5.2
cloth_config_version=26.1.154