org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

mod_id=cinderlib
mod_name=CinderLib
mod_version=0.1.0
mod_group=net.cinderlabsmc

minecraft_version=26.3
java_version=25

fabric_loom_version=1.18.2
fabric_loader_version=0.19.5
neoforge_version=26.3.0.8-beta
moddev_version=2.0.147
architectury_api_version=22.0.2
architectury_injectables_version=1.0.10
geckolib_version=5.5.7