modLoader = "javafml"
loaderVersion = "[1,)"
license = "All-Rights-Reserved"
issueTrackerURL = "https://github.com/ezTxmMC/cinderlib/issues"

[[mods]]
modId = "cinderlib"
version = "${version}"
displayName = "CinderLib"
description = "CinderLib mod."
authors = "ezTxmMC"

[[dependencies.cinderlib]]
    modId = "neoforge"
    type = "required"
    versionRange = "[26.1.2,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.cinderlib]]
    modId = "minecraft"
    type = "required"
    versionRange = "[26.1.2,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.cinderlib]]
    modId = "architectury"
    type = "required"
    versionRange = "[20.1.15,)"
    ordering = "AFTER"
    side = "BOTH"
