plugins {
    id 'net.neoforged.moddev' version "${moddev_version}"
}

neoForge {
    version = neoforge_version

    runs {
        client { client() }
        server { server() }
        data {
            serverData()
            programArguments.addAll '--mod', mod_id, '--all',
                    '--output', rootProject.file('common/src/generated/resources').absolutePath,
                    '--existing', rootProject.file('common/src/main/resources').absolutePath
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet project(':common').sourceSets.main
        }
    }
}

dependencies {
    implementation "dev.architectury:architectury-neoforge:${architectury_api_version}"
    compileOnly project(':common')
}

tasks.jar {
    from project(':common').sourceSets.main.output
}