package net.cinderlabsmc.cinderlib.example;

import net.cinderlabsmc.cinderlib.datagen.CinderDataGen;
import net.cinderlabsmc.cinderlib.worldgen.CinderOre;

/**
 * Example worldgen definitions, generated by {@link ExampleDataGen}. Each ore
 * writes a configured feature, a placed
 * feature and a NeoForge biome modifier under {@code data/cinderexample/}.
 */
public final class ExampleWorldgen {

  /**
   * Vanilla-like ore: stone and deepslate variant, common, spread over the whole
   * underground.
   */
  public static final CinderOre RUBY = CinderOre.of("ruby_ore")
      .block("cinderexample:ruby_ore")
      .deepslate("cinderexample:deepslate_ruby_ore")
      .size(6)
      .count(4)
      .height(-64, 16);

  /**
   * Big rare-ish vein of a decorative block, only near the surface and only in
   * mountain biomes.
   */
  public static final CinderOre MARBLE = CinderOre.of("marble")
      .block("cinderexample:marble")
      .size(33)
      .count(2)
      .height(48, 160)
      .biomes("#minecraft:is_mountain");

  /**
   * Diamond-like ore that hides from caves: veins touching air are mostly
   * skipped.
   */
  public static final CinderOre HIDDEN_RUBY = CinderOre.of("hidden_ruby_ore")
      .block("cinderexample:ruby_ore")
      .deepslate("cinderexample:deepslate_ruby_ore")
      .size(4)
      .count(1)
      .height(-64, -32)
      .hideFromAir(0.9f);

  public static void generate(CinderDataGen data) {
    data.apply(RUBY).apply(MARBLE).apply(HIDDEN_RUBY);
  }

  private ExampleWorldgen() {
  }
}
